Algoritmo "ColetaDeDados"

Var
    email: caractere
    Nome: caractere
    telefone: caractere

Inicio
      escreval ("Digite seu email: ")
      leia (email)
      escreval ("Digite seu nome: ")
      leia (nome)
      escreval ("Digite seu telefone: (ex: DDD999999999)")
      leia (telefone)
      escreval ("Confirme seus dados!")
      escreval (nome+" ",+ email+" ",+ telefone)

Fimalgoritmo
