
Var
   x, y : real
Inicio
   escreva ("digite o valor de y: ")
   leia (y)
   escreva ("digite o valor de x: ")
   leia (x)
   se (y > 0) e (x < 0) entao
      escreva ("Q2")
   fimse
   se (y < 0) e (x > 0) entao
      escreva ("Q4")
   fimse
   se (y > 0)  e (x > 0) entao
      escreva ("Q1")
   fimse
   se (y < 0) e (x < 0) entao
      escreva ("Q3")
   fimse
   se (y = 0) e (x = 0) entao
      escreva ("Origem")
   fimse

Fimalgoritmo
