Algoritmo "salario"

Var
   pessoa1, pessoa2: caractere
 ValorHora, salario1, salario2, horas,soma: real

Inicio

      escreva ("Nome do funcionário(a): ")
      leia (pessoa1)
escreva ("Digite a quantidade de horas trabalhadas: ")
      leia (horas)
        ValorHora <- 90.00
      soma <- (salario1 + salario2)
      salario1 <- (ValorHora * horas)
      salario2 <- (ValorHora * horas)

      escreval (" O salário de ", pessoa1, " é ", salario1, " reais.")

Fimalgoritmo
